--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2026-01-29 09:49:39

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 35320)
-- Name: meta; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA meta;


ALTER SCHEMA meta OWNER TO postgres;

--
-- TOC entry 6 (class 2615 OID 35321)
-- Name: pgagent; Type: SCHEMA; Schema: -; Owner: alberto.vicente
--

CREATE SCHEMA pgagent;


ALTER SCHEMA pgagent OWNER TO "alberto.vicente";

--
-- TOC entry 5142 (class 0 OID 0)
-- Dependencies: 6
-- Name: SCHEMA pgagent; Type: COMMENT; Schema: -; Owner: alberto.vicente
--

COMMENT ON SCHEMA pgagent IS 'pgAgent system tables';


--
-- TOC entry 896 (class 1247 OID 35323)
-- Name: data_type_enum; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.data_type_enum AS ENUM (
    'uint8',
    'uint16',
    'float32',
    'float64'
);


ALTER TYPE public.data_type_enum OWNER TO postgres;

--
-- TOC entry 899 (class 1247 OID 35332)
-- Name: file_type_enum; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.file_type_enum AS ENUM (
    'tiff',
    'raw',
    'jpeg',
    'png'
);


ALTER TYPE public.file_type_enum OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 35341)
-- Name: migrations; Type: TABLE; Schema: meta; Owner: postgres
--

CREATE TABLE meta.migrations (
    version text NOT NULL,
    name text,
    applied_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE meta.migrations OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 35350)
-- Name: dataset_metadata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dataset_metadata (
    id bigint NOT NULL,
    dataset_id bigint NOT NULL,
    key text NOT NULL,
    value text,
    type text,
    extra_info json
);


ALTER TABLE public.dataset_metadata OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 35355)
-- Name: dataset_metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dataset_metadata ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.dataset_metadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 35347)
-- Name: dataset_registrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dataset_registrations (
    id bigint NOT NULL,
    dataset_id bigint NOT NULL,
    registration_id bigint NOT NULL
);


ALTER TABLE public.dataset_registrations OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 35356)
-- Name: datasetmeasurements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dataset_registrations ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.datasetmeasurements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 35357)
-- Name: datasets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.datasets (
    id bigint NOT NULL,
    file_path text NOT NULL,
    description text,
    datasettype_id bigint NOT NULL
);


ALTER TABLE public.datasets OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 35362)
-- Name: datasets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.datasets ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.datasets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 43176)
-- Name: datasettypes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.datasettypes (
    id bigint NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.datasettypes OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 43190)
-- Name: datasettypes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.datasettypes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.datasettypes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 267 (class 1259 OID 43278)
-- Name: experiment_datasets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.experiment_datasets (
    id integer NOT NULL,
    experiment_id integer NOT NULL,
    dataset_id bigint NOT NULL
);


ALTER TABLE public.experiment_datasets OWNER TO postgres;

--
-- TOC entry 266 (class 1259 OID 43277)
-- Name: experiment_datasets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.experiment_datasets_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.experiment_datasets_id_seq OWNER TO postgres;

--
-- TOC entry 5147 (class 0 OID 0)
-- Dependencies: 266
-- Name: experiment_datasets_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.experiment_datasets_id_seq OWNED BY public.experiment_datasets.id;


--
-- TOC entry 261 (class 1259 OID 43215)
-- Name: experiment_metadata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.experiment_metadata (
    id integer NOT NULL,
    experiment_id integer NOT NULL,
    key character varying(255) NOT NULL,
    value text,
    type character varying(100),
    extra_info jsonb
);


ALTER TABLE public.experiment_metadata OWNER TO postgres;

--
-- TOC entry 260 (class 1259 OID 43214)
-- Name: experiment_metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.experiment_metadata_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.experiment_metadata_id_seq OWNER TO postgres;

--
-- TOC entry 5148 (class 0 OID 0)
-- Dependencies: 260
-- Name: experiment_metadata_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.experiment_metadata_id_seq OWNED BY public.experiment_metadata.id;


--
-- TOC entry 259 (class 1259 OID 43204)
-- Name: experiments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.experiments (
    id integer NOT NULL,
    folder_path text NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.experiments OWNER TO postgres;

--
-- TOC entry 258 (class 1259 OID 43203)
-- Name: experiments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.experiments_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.experiments_id_seq OWNER TO postgres;

--
-- TOC entry 5149 (class 0 OID 0)
-- Dependencies: 258
-- Name: experiments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.experiments_id_seq OWNED BY public.experiments.id;


--
-- TOC entry 226 (class 1259 OID 35363)
-- Name: fabrications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fabrications (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    description text
);


ALTER TABLE public.fabrications OWNER TO postgres;

--
-- TOC entry 5150 (class 0 OID 0)
-- Dependencies: 226
-- Name: TABLE fabrications; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.fabrications IS 'Stores information about distinct fabrication processes or methods.';


--
-- TOC entry 227 (class 1259 OID 35368)
-- Name: fabrication_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fabrication_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.fabrication_id_seq OWNER TO postgres;

--
-- TOC entry 5151 (class 0 OID 0)
-- Dependencies: 227
-- Name: fabrication_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.fabrication_id_seq OWNED BY public.fabrications.id;


--
-- TOC entry 228 (class 1259 OID 35369)
-- Name: fabrication_metadata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fabrication_metadata (
    id integer NOT NULL,
    fabrication_id integer NOT NULL,
    key character varying(255) NOT NULL,
    value text NOT NULL,
    type character varying(100),
    extra_info jsonb
);


ALTER TABLE public.fabrication_metadata OWNER TO postgres;

--
-- TOC entry 5152 (class 0 OID 0)
-- Dependencies: 228
-- Name: TABLE fabrication_metadata; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.fabrication_metadata IS 'Stores flexible key-value metadata for each entry in the fabrication table.';


--
-- TOC entry 229 (class 1259 OID 35374)
-- Name: fabrication_metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fabrication_metadata_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.fabrication_metadata_id_seq OWNER TO postgres;

--
-- TOC entry 5153 (class 0 OID 0)
-- Dependencies: 229
-- Name: fabrication_metadata_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.fabrication_metadata_id_seq OWNED BY public.fabrication_metadata.id;


--
-- TOC entry 230 (class 1259 OID 35375)
-- Name: registrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.registrations (
    id bigint NOT NULL,
    reference_measurement_id bigint NOT NULL,
    registered_measurement_id bigint NOT NULL,
    registration_matrix text NOT NULL,
    description text
);


ALTER TABLE public.registrations OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 35380)
-- Name: file_registrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.registrations ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.file_registrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 35381)
-- Name: material_metadata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.material_metadata (
    id bigint NOT NULL,
    material_id bigint NOT NULL,
    key text NOT NULL,
    value text NOT NULL,
    type text,
    extra_info json
);


ALTER TABLE public.material_metadata OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 35386)
-- Name: material_metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.material_metadata ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.material_metadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 35387)
-- Name: materials; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.materials (
    id bigint NOT NULL,
    name text NOT NULL
);


ALTER TABLE public.materials OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 35392)
-- Name: materials_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.materials ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.materials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 35393)
-- Name: measurements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.measurements (
    id bigint NOT NULL,
    file_path text NOT NULL,
    parent_measurement_id bigint,
    measurementtype_id bigint NOT NULL
);


ALTER TABLE public.measurements OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 35398)
-- Name: measurement_files_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.measurements ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.measurement_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 35399)
-- Name: measurement_metadata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.measurement_metadata (
    id bigint NOT NULL,
    measurement_id bigint NOT NULL,
    key text NOT NULL,
    value text,
    type text,
    extra_info json
);


ALTER TABLE public.measurement_metadata OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 35404)
-- Name: measurement_files_metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.measurement_metadata ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.measurement_files_metadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 35405)
-- Name: registration_metadata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.registration_metadata (
    id integer NOT NULL,
    registration_id integer NOT NULL,
    key character varying(255) NOT NULL,
    value text NOT NULL,
    type character varying(100),
    extra_info jsonb
);


ALTER TABLE public.registration_metadata OWNER TO postgres;

--
-- TOC entry 5159 (class 0 OID 0)
-- Dependencies: 240
-- Name: TABLE registration_metadata; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.registration_metadata IS 'Stores flexible key-value metadata for each entry in the measurement_registrations table.';


--
-- TOC entry 241 (class 1259 OID 35410)
-- Name: measurement_registration_metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.measurement_registration_metadata_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.measurement_registration_metadata_id_seq OWNER TO postgres;

--
-- TOC entry 5160 (class 0 OID 0)
-- Dependencies: 241
-- Name: measurement_registration_metadata_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.measurement_registration_metadata_id_seq OWNED BY public.registration_metadata.id;


--
-- TOC entry 242 (class 1259 OID 35411)
-- Name: measurementtype_metadata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.measurementtype_metadata (
    id bigint NOT NULL,
    measurementtype_id bigint,
    key text NOT NULL,
    value text,
    type text,
    extra_info json
);


ALTER TABLE public.measurementtype_metadata OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 35416)
-- Name: measurement_type_metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.measurementtype_metadata ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.measurement_type_metadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 35417)
-- Name: measurementtypes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.measurementtypes (
    id bigint NOT NULL,
    name text NOT NULL,
    description text
);


ALTER TABLE public.measurementtypes OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 35422)
-- Name: measurementtypes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.measurementtypes ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.measurementtypes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 265 (class 1259 OID 43262)
-- Name: model_metadata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.model_metadata (
    id integer NOT NULL,
    model_id integer NOT NULL,
    key character varying(255) NOT NULL,
    value text,
    type character varying(100),
    extra_info jsonb
);


ALTER TABLE public.model_metadata OWNER TO postgres;

--
-- TOC entry 264 (class 1259 OID 43261)
-- Name: model_metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.model_metadata_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.model_metadata_id_seq OWNER TO postgres;

--
-- TOC entry 5163 (class 0 OID 0)
-- Dependencies: 264
-- Name: model_metadata_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.model_metadata_id_seq OWNED BY public.model_metadata.id;


--
-- TOC entry 263 (class 1259 OID 43246)
-- Name: models; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.models (
    id integer NOT NULL,
    experiment_id integer NOT NULL,
    model_folder_path text NOT NULL,
    description text
);


ALTER TABLE public.models OWNER TO postgres;

--
-- TOC entry 262 (class 1259 OID 43245)
-- Name: models_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.models_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.models_id_seq OWNER TO postgres;

--
-- TOC entry 5164 (class 0 OID 0)
-- Dependencies: 262
-- Name: models_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.models_id_seq OWNED BY public.models.id;


--
-- TOC entry 246 (class 1259 OID 35423)
-- Name: panels; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.panels (
    id bigint NOT NULL,
    name text NOT NULL,
    material_id bigint NOT NULL,
    description text,
    fabrication_id integer
);


ALTER TABLE public.panels OWNER TO postgres;

--
-- TOC entry 5165 (class 0 OID 0)
-- Dependencies: 246
-- Name: COLUMN panels.fabrication_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.panels.fabrication_id IS 'Foreign key referencing the fabrication method used to create the panel.';


--
-- TOC entry 247 (class 1259 OID 35428)
-- Name: panel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.panels ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.panel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 35429)
-- Name: panel_metadata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.panel_metadata (
    id bigint NOT NULL,
    panel_id bigint NOT NULL,
    key text NOT NULL,
    value text,
    type text,
    extra_info json
);


ALTER TABLE public.panel_metadata OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 35434)
-- Name: panel_metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.panel_metadata ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.panel_metadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 35435)
-- Name: sample_measurements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sample_measurements (
    id bigint NOT NULL,
    sample_id bigint NOT NULL,
    measurement_id bigint NOT NULL
);


ALTER TABLE public.sample_measurements OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 35438)
-- Name: sample_measurements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sample_measurements ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.sample_measurements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 35439)
-- Name: sample_metadata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sample_metadata (
    id bigint NOT NULL,
    sample_id bigint NOT NULL,
    key text NOT NULL,
    value text,
    type text,
    extra_info json
);


ALTER TABLE public.sample_metadata OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 35444)
-- Name: sample_metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sample_metadata ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.sample_metadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 35445)
-- Name: samples; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.samples (
    id bigint NOT NULL,
    name text NOT NULL,
    description text,
    panel_id bigint NOT NULL
);


ALTER TABLE public.samples OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 35450)
-- Name: samples_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.samples ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.samples_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4878 (class 2604 OID 43281)
-- Name: experiment_datasets id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiment_datasets ALTER COLUMN id SET DEFAULT nextval('public.experiment_datasets_id_seq'::regclass);


--
-- TOC entry 4875 (class 2604 OID 43218)
-- Name: experiment_metadata id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiment_metadata ALTER COLUMN id SET DEFAULT nextval('public.experiment_metadata_id_seq'::regclass);


--
-- TOC entry 4874 (class 2604 OID 43207)
-- Name: experiments id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiments ALTER COLUMN id SET DEFAULT nextval('public.experiments_id_seq'::regclass);


--
-- TOC entry 4872 (class 2604 OID 35452)
-- Name: fabrication_metadata id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fabrication_metadata ALTER COLUMN id SET DEFAULT nextval('public.fabrication_metadata_id_seq'::regclass);


--
-- TOC entry 4871 (class 2604 OID 35451)
-- Name: fabrications id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fabrications ALTER COLUMN id SET DEFAULT nextval('public.fabrication_id_seq'::regclass);


--
-- TOC entry 4877 (class 2604 OID 43265)
-- Name: model_metadata id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.model_metadata ALTER COLUMN id SET DEFAULT nextval('public.model_metadata_id_seq'::regclass);


--
-- TOC entry 4876 (class 2604 OID 43249)
-- Name: models id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.models ALTER COLUMN id SET DEFAULT nextval('public.models_id_seq'::regclass);


--
-- TOC entry 4873 (class 2604 OID 35453)
-- Name: registration_metadata id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registration_metadata ALTER COLUMN id SET DEFAULT nextval('public.measurement_registration_metadata_id_seq'::regclass);


--
-- TOC entry 4880 (class 2606 OID 35455)
-- Name: migrations migrations_pkey; Type: CONSTRAINT; Schema: meta; Owner: postgres
--

ALTER TABLE ONLY meta.migrations
    ADD CONSTRAINT migrations_pkey PRIMARY KEY (version);


--
-- TOC entry 4886 (class 2606 OID 35457)
-- Name: dataset_metadata dataset_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dataset_metadata
    ADD CONSTRAINT dataset_metadata_pkey PRIMARY KEY (id);


--
-- TOC entry 4882 (class 2606 OID 35459)
-- Name: dataset_registrations datasetmeasurements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dataset_registrations
    ADD CONSTRAINT datasetmeasurements_pkey PRIMARY KEY (id);


--
-- TOC entry 4889 (class 2606 OID 35461)
-- Name: datasets datasets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.datasets
    ADD CONSTRAINT datasets_pkey PRIMARY KEY (id);


--
-- TOC entry 4944 (class 2606 OID 43182)
-- Name: datasettypes datasettypes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.datasettypes
    ADD CONSTRAINT datasettypes_pkey PRIMARY KEY (id);


--
-- TOC entry 4964 (class 2606 OID 43285)
-- Name: experiment_datasets experiment_datasets_experiment_id_dataset_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiment_datasets
    ADD CONSTRAINT experiment_datasets_experiment_id_dataset_id_key UNIQUE (experiment_id, dataset_id);


--
-- TOC entry 4966 (class 2606 OID 43283)
-- Name: experiment_datasets experiment_datasets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiment_datasets
    ADD CONSTRAINT experiment_datasets_pkey PRIMARY KEY (id);


--
-- TOC entry 4952 (class 2606 OID 43224)
-- Name: experiment_metadata experiment_metadata_experiment_id_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiment_metadata
    ADD CONSTRAINT experiment_metadata_experiment_id_key_key UNIQUE (experiment_id, key);


--
-- TOC entry 4954 (class 2606 OID 43222)
-- Name: experiment_metadata experiment_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiment_metadata
    ADD CONSTRAINT experiment_metadata_pkey PRIMARY KEY (id);


--
-- TOC entry 4948 (class 2606 OID 43213)
-- Name: experiments experiments_folder_path_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiments
    ADD CONSTRAINT experiments_folder_path_key UNIQUE (folder_path);


--
-- TOC entry 4950 (class 2606 OID 43211)
-- Name: experiments experiments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiments
    ADD CONSTRAINT experiments_pkey PRIMARY KEY (id);


--
-- TOC entry 4897 (class 2606 OID 35463)
-- Name: fabrication_metadata fabrication_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fabrication_metadata
    ADD CONSTRAINT fabrication_metadata_pkey PRIMARY KEY (id);


--
-- TOC entry 4893 (class 2606 OID 35465)
-- Name: fabrications fabrication_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fabrications
    ADD CONSTRAINT fabrication_name_key UNIQUE (name);


--
-- TOC entry 4895 (class 2606 OID 35467)
-- Name: fabrications fabrication_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fabrications
    ADD CONSTRAINT fabrication_pkey PRIMARY KEY (id);


--
-- TOC entry 4899 (class 2606 OID 35469)
-- Name: registrations file_registrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registrations
    ADD CONSTRAINT file_registrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4904 (class 2606 OID 35471)
-- Name: material_metadata material_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.material_metadata
    ADD CONSTRAINT material_metadata_pkey PRIMARY KEY (id);


--
-- TOC entry 4906 (class 2606 OID 35473)
-- Name: materials materials_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.materials
    ADD CONSTRAINT materials_pkey PRIMARY KEY (id);


--
-- TOC entry 4910 (class 2606 OID 35475)
-- Name: measurements measurement_files_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.measurements
    ADD CONSTRAINT measurement_files_pkey PRIMARY KEY (id);


--
-- TOC entry 4915 (class 2606 OID 35477)
-- Name: measurement_metadata measurement_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.measurement_metadata
    ADD CONSTRAINT measurement_metadata_pkey PRIMARY KEY (id);


--
-- TOC entry 4917 (class 2606 OID 35479)
-- Name: registration_metadata measurement_registration_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registration_metadata
    ADD CONSTRAINT measurement_registration_metadata_pkey PRIMARY KEY (id);


--
-- TOC entry 4920 (class 2606 OID 35481)
-- Name: measurementtype_metadata measurement_type_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.measurementtype_metadata
    ADD CONSTRAINT measurement_type_metadata_pkey PRIMARY KEY (id);


--
-- TOC entry 4922 (class 2606 OID 35483)
-- Name: measurementtypes measurementtypes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.measurementtypes
    ADD CONSTRAINT measurementtypes_pkey PRIMARY KEY (id);


--
-- TOC entry 4960 (class 2606 OID 43271)
-- Name: model_metadata model_metadata_model_id_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.model_metadata
    ADD CONSTRAINT model_metadata_model_id_key_key UNIQUE (model_id, key);


--
-- TOC entry 4962 (class 2606 OID 43269)
-- Name: model_metadata model_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.model_metadata
    ADD CONSTRAINT model_metadata_pkey PRIMARY KEY (id);


--
-- TOC entry 4956 (class 2606 OID 43255)
-- Name: models models_model_folder_path_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.models
    ADD CONSTRAINT models_model_folder_path_key UNIQUE (model_folder_path);


--
-- TOC entry 4958 (class 2606 OID 43253)
-- Name: models models_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.models
    ADD CONSTRAINT models_pkey PRIMARY KEY (id);


--
-- TOC entry 4931 (class 2606 OID 35485)
-- Name: panel_metadata panel_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.panel_metadata
    ADD CONSTRAINT panel_metadata_pkey PRIMARY KEY (id);


--
-- TOC entry 4926 (class 2606 OID 35487)
-- Name: panels panel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.panels
    ADD CONSTRAINT panel_pkey PRIMARY KEY (id);


--
-- TOC entry 4935 (class 2606 OID 35489)
-- Name: sample_measurements sample_measurements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sample_measurements
    ADD CONSTRAINT sample_measurements_pkey PRIMARY KEY (id);


--
-- TOC entry 4938 (class 2606 OID 35491)
-- Name: sample_metadata sample_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sample_metadata
    ADD CONSTRAINT sample_metadata_pkey PRIMARY KEY (id);


--
-- TOC entry 4940 (class 2606 OID 35493)
-- Name: samples samples_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_pkey PRIMARY KEY (id);


--
-- TOC entry 4891 (class 2606 OID 35495)
-- Name: datasets unique_datasets_name; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.datasets
    ADD CONSTRAINT unique_datasets_name UNIQUE (file_path);


--
-- TOC entry 4946 (class 2606 OID 43189)
-- Name: datasettypes unique_datasettype_description; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.datasettypes
    ADD CONSTRAINT unique_datasettype_description UNIQUE (description);


--
-- TOC entry 4912 (class 2606 OID 35497)
-- Name: measurements unique_file_path; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.measurements
    ADD CONSTRAINT unique_file_path UNIQUE (file_path);


--
-- TOC entry 4908 (class 2606 OID 35499)
-- Name: materials unique_materials_name; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.materials
    ADD CONSTRAINT unique_materials_name UNIQUE (name);


--
-- TOC entry 4924 (class 2606 OID 35501)
-- Name: measurementtypes unique_measurementtypes_name; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.measurementtypes
    ADD CONSTRAINT unique_measurementtypes_name UNIQUE (name);


--
-- TOC entry 4928 (class 2606 OID 35503)
-- Name: panels unique_panels_name; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.panels
    ADD CONSTRAINT unique_panels_name UNIQUE (name);


--
-- TOC entry 4942 (class 2606 OID 35505)
-- Name: samples unique_samples_name; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT unique_samples_name UNIQUE (name);


--
-- TOC entry 4887 (class 1259 OID 35506)
-- Name: fki_dataset_metadata_dataset_id_fkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_dataset_metadata_dataset_id_fkey ON public.dataset_metadata USING btree (dataset_id);


--
-- TOC entry 4883 (class 1259 OID 35507)
-- Name: fki_datasetmeasurements_dataset_id_fkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_datasetmeasurements_dataset_id_fkey ON public.dataset_registrations USING btree (dataset_id);


--
-- TOC entry 4884 (class 1259 OID 35508)
-- Name: fki_datasetmeasurements_measurement_file_id_fkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_datasetmeasurements_measurement_file_id_fkey ON public.dataset_registrations USING btree (registration_id);


--
-- TOC entry 4900 (class 1259 OID 35509)
-- Name: fki_file_registrations_reference_file_id_fkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_file_registrations_reference_file_id_fkey ON public.registrations USING btree (reference_measurement_id);


--
-- TOC entry 4901 (class 1259 OID 35510)
-- Name: fki_file_registrations_registered_file_id_fkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_file_registrations_registered_file_id_fkey ON public.registrations USING btree (registered_measurement_id);


--
-- TOC entry 4902 (class 1259 OID 35511)
-- Name: fki_material_metadata_material_id_fkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_material_metadata_material_id_fkey ON public.material_metadata USING btree (material_id);


--
-- TOC entry 4932 (class 1259 OID 35512)
-- Name: fki_measurement_fkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_measurement_fkey ON public.sample_measurements USING btree (measurement_id);


--
-- TOC entry 4913 (class 1259 OID 35513)
-- Name: fki_measurement_metadata_measurement_id_fkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_measurement_metadata_measurement_id_fkey ON public.measurement_metadata USING btree (measurement_id);


--
-- TOC entry 4918 (class 1259 OID 35514)
-- Name: fki_measurement_type_metadata_measurement_type_id_fkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_measurement_type_metadata_measurement_type_id_fkey ON public.measurementtype_metadata USING btree (measurementtype_id);


--
-- TOC entry 4929 (class 1259 OID 35515)
-- Name: fki_panel_metadata_panel_id_fkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_panel_metadata_panel_id_fkey ON public.panel_metadata USING btree (panel_id);


--
-- TOC entry 4933 (class 1259 OID 35516)
-- Name: fki_sample_fkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_sample_fkey ON public.sample_measurements USING btree (sample_id);


--
-- TOC entry 4936 (class 1259 OID 35517)
-- Name: fki_sample_metadata_sample_id_fkey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_sample_metadata_sample_id_fkey ON public.sample_metadata USING btree (sample_id);


--
-- TOC entry 4969 (class 2606 OID 35518)
-- Name: dataset_metadata dataset_metadata_dataset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dataset_metadata
    ADD CONSTRAINT dataset_metadata_dataset_id_fkey FOREIGN KEY (dataset_id) REFERENCES public.datasets(id) ON DELETE CASCADE;


--
-- TOC entry 4967 (class 2606 OID 35523)
-- Name: dataset_registrations datasetregistrations_dataset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dataset_registrations
    ADD CONSTRAINT datasetregistrations_dataset_id_fkey FOREIGN KEY (dataset_id) REFERENCES public.datasets(id) ON DELETE CASCADE;


--
-- TOC entry 4968 (class 2606 OID 43309)
-- Name: dataset_registrations datasetregistrations_registration_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dataset_registrations
    ADD CONSTRAINT datasetregistrations_registration_id_fkey FOREIGN KEY (registration_id) REFERENCES public.registrations(id) ON DELETE CASCADE NOT VALID;


--
-- TOC entry 4970 (class 2606 OID 43183)
-- Name: datasets datasets_datasettype_foreign_key; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.datasets
    ADD CONSTRAINT datasets_datasettype_foreign_key FOREIGN KEY (datasettype_id) REFERENCES public.datasettypes(id) NOT VALID;


--
-- TOC entry 4990 (class 2606 OID 43291)
-- Name: experiment_datasets experiment_datasets_dataset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiment_datasets
    ADD CONSTRAINT experiment_datasets_dataset_id_fkey FOREIGN KEY (dataset_id) REFERENCES public.datasets(id) ON DELETE CASCADE;


--
-- TOC entry 4991 (class 2606 OID 43286)
-- Name: experiment_datasets experiment_datasets_experiment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiment_datasets
    ADD CONSTRAINT experiment_datasets_experiment_id_fkey FOREIGN KEY (experiment_id) REFERENCES public.experiments(id) ON DELETE CASCADE;


--
-- TOC entry 4987 (class 2606 OID 43225)
-- Name: experiment_metadata experiment_metadata_experiment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.experiment_metadata
    ADD CONSTRAINT experiment_metadata_experiment_id_fkey FOREIGN KEY (experiment_id) REFERENCES public.experiments(id) ON DELETE CASCADE;


--
-- TOC entry 4971 (class 2606 OID 35533)
-- Name: fabrication_metadata fabrication_metadata_fabrication_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fabrication_metadata
    ADD CONSTRAINT fabrication_metadata_fabrication_id_fkey FOREIGN KEY (fabrication_id) REFERENCES public.fabrications(id) ON DELETE CASCADE;


--
-- TOC entry 4972 (class 2606 OID 35538)
-- Name: registrations file_registrations_reference_file_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registrations
    ADD CONSTRAINT file_registrations_reference_file_id_fkey FOREIGN KEY (reference_measurement_id) REFERENCES public.measurements(id) ON DELETE CASCADE;


--
-- TOC entry 4973 (class 2606 OID 35543)
-- Name: registrations file_registrations_registered_file_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registrations
    ADD CONSTRAINT file_registrations_registered_file_id_fkey FOREIGN KEY (registered_measurement_id) REFERENCES public.measurements(id) ON DELETE CASCADE;


--
-- TOC entry 4974 (class 2606 OID 35548)
-- Name: material_metadata material_metadata_material_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.material_metadata
    ADD CONSTRAINT material_metadata_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.materials(id) ON DELETE CASCADE;


--
-- TOC entry 4975 (class 2606 OID 35553)
-- Name: measurements measurement_files_measurementtype_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.measurements
    ADD CONSTRAINT measurement_files_measurementtype_id_fkey FOREIGN KEY (measurementtype_id) REFERENCES public.measurementtypes(id);


--
-- TOC entry 4976 (class 2606 OID 35558)
-- Name: measurements measurement_files_parent_file_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.measurements
    ADD CONSTRAINT measurement_files_parent_file_id_fkey FOREIGN KEY (parent_measurement_id) REFERENCES public.measurements(id);


--
-- TOC entry 4977 (class 2606 OID 35563)
-- Name: measurement_metadata measurement_metadata_measurement_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.measurement_metadata
    ADD CONSTRAINT measurement_metadata_measurement_id_fkey FOREIGN KEY (measurement_id) REFERENCES public.measurements(id) ON DELETE CASCADE;


--
-- TOC entry 4978 (class 2606 OID 35568)
-- Name: registration_metadata measurement_registration_metad_measurement_registration_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registration_metadata
    ADD CONSTRAINT measurement_registration_metad_measurement_registration_id_fkey FOREIGN KEY (registration_id) REFERENCES public.registrations(id) ON DELETE CASCADE;


--
-- TOC entry 4979 (class 2606 OID 35573)
-- Name: measurementtype_metadata measurement_type_metadata_measurement_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.measurementtype_metadata
    ADD CONSTRAINT measurement_type_metadata_measurement_type_id_fkey FOREIGN KEY (measurementtype_id) REFERENCES public.measurementtypes(id) ON DELETE CASCADE;


--
-- TOC entry 4989 (class 2606 OID 43272)
-- Name: model_metadata model_metadata_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.model_metadata
    ADD CONSTRAINT model_metadata_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.models(id) ON DELETE CASCADE;


--
-- TOC entry 4988 (class 2606 OID 43256)
-- Name: models models_experiment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.models
    ADD CONSTRAINT models_experiment_id_fkey FOREIGN KEY (experiment_id) REFERENCES public.experiments(id) ON DELETE CASCADE;


--
-- TOC entry 4980 (class 2606 OID 35578)
-- Name: panels panel_material_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.panels
    ADD CONSTRAINT panel_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.materials(id);


--
-- TOC entry 4982 (class 2606 OID 35583)
-- Name: panel_metadata panel_metadata_panel_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.panel_metadata
    ADD CONSTRAINT panel_metadata_panel_id_fkey FOREIGN KEY (panel_id) REFERENCES public.panels(id) ON DELETE CASCADE;


--
-- TOC entry 4981 (class 2606 OID 35588)
-- Name: panels panels_fabrication_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.panels
    ADD CONSTRAINT panels_fabrication_id_fkey FOREIGN KEY (fabrication_id) REFERENCES public.fabrications(id);


--
-- TOC entry 4983 (class 2606 OID 35593)
-- Name: sample_measurements sample_measurements_measurement_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sample_measurements
    ADD CONSTRAINT sample_measurements_measurement_fkey FOREIGN KEY (measurement_id) REFERENCES public.measurements(id) ON DELETE CASCADE;


--
-- TOC entry 4984 (class 2606 OID 35598)
-- Name: sample_measurements sample_measurements_sample_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sample_measurements
    ADD CONSTRAINT sample_measurements_sample_fkey FOREIGN KEY (sample_id) REFERENCES public.samples(id) ON DELETE CASCADE;


--
-- TOC entry 4985 (class 2606 OID 35603)
-- Name: sample_metadata sample_metadata_sample_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sample_metadata
    ADD CONSTRAINT sample_metadata_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES public.samples(id) ON DELETE CASCADE;


--
-- TOC entry 4986 (class 2606 OID 35608)
-- Name: samples samples_panel_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_panel_id_fkey FOREIGN KEY (panel_id) REFERENCES public.panels(id);


--
-- TOC entry 5143 (class 0 OID 0)
-- Dependencies: 7
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO "ignacio.racano";
GRANT ALL ON SCHEMA public TO "jorge.cabrejas";


--
-- TOC entry 5144 (class 0 OID 0)
-- Dependencies: 221
-- Name: TABLE dataset_metadata; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.dataset_metadata TO "ignacio.racano";


--
-- TOC entry 5145 (class 0 OID 0)
-- Dependencies: 220
-- Name: TABLE dataset_registrations; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.dataset_registrations TO "ignacio.racano";


--
-- TOC entry 5146 (class 0 OID 0)
-- Dependencies: 224
-- Name: TABLE datasets; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT ON TABLE public.datasets TO "ignacio.racano";


--
-- TOC entry 5154 (class 0 OID 0)
-- Dependencies: 230
-- Name: TABLE registrations; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.registrations TO "ignacio.racano";


--
-- TOC entry 5155 (class 0 OID 0)
-- Dependencies: 232
-- Name: TABLE material_metadata; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.material_metadata TO "ignacio.racano";


--
-- TOC entry 5156 (class 0 OID 0)
-- Dependencies: 234
-- Name: TABLE materials; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.materials TO "ignacio.racano";


--
-- TOC entry 5157 (class 0 OID 0)
-- Dependencies: 236
-- Name: TABLE measurements; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.measurements TO "ignacio.racano";


--
-- TOC entry 5158 (class 0 OID 0)
-- Dependencies: 238
-- Name: TABLE measurement_metadata; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.measurement_metadata TO "ignacio.racano";


--
-- TOC entry 5161 (class 0 OID 0)
-- Dependencies: 242
-- Name: TABLE measurementtype_metadata; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.measurementtype_metadata TO "ignacio.racano";


--
-- TOC entry 5162 (class 0 OID 0)
-- Dependencies: 244
-- Name: TABLE measurementtypes; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.measurementtypes TO "ignacio.racano";


--
-- TOC entry 5166 (class 0 OID 0)
-- Dependencies: 246
-- Name: TABLE panels; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.panels TO "ignacio.racano";


--
-- TOC entry 5167 (class 0 OID 0)
-- Dependencies: 248
-- Name: TABLE panel_metadata; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.panel_metadata TO "ignacio.racano";


--
-- TOC entry 5168 (class 0 OID 0)
-- Dependencies: 250
-- Name: TABLE sample_measurements; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.sample_measurements TO "ignacio.racano";


--
-- TOC entry 5169 (class 0 OID 0)
-- Dependencies: 252
-- Name: TABLE sample_metadata; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.sample_metadata TO "ignacio.racano";


--
-- TOC entry 5170 (class 0 OID 0)
-- Dependencies: 254
-- Name: TABLE samples; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.samples TO "ignacio.racano";


--
-- TOC entry 2171 (class 826 OID 35613)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: alberto.vicente
--

ALTER DEFAULT PRIVILEGES FOR ROLE "alberto.vicente" IN SCHEMA public GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO "ignacio.racano";


-- Completed on 2026-01-29 09:49:39

--
-- PostgreSQL database dump complete
--

